### PR TITLE
Search pull requests and fix parse bug

### PR DESCRIPTION
**Pull request by beaugunderson**
I actually managed to implement both pieces of #2. :sparkles:
- package.json in the default branch is now searched for a valid license
- if package.json appears in any pull requests they're searched for a valid license
- `github-url-to-object` does't handle URLs like 'git+ssh://' correctly so I strip off 'git+' from the beginning

I tried to keep a similar code style but did find it necessary to break things out into functions to understand what was going on. I also opted for (slightly) more vertical whitespace in the code I added but let me know if you want that removed. :)

You can [see how it looks here](https://beaugunderson.com/npm1k.html). Note that the pull request links are wrong in that version (they're API links there) but if you regenerate (after putting a token in your environment in `GITHUB_TOKEN`) you'll see the correct URLs. I'll also regenerate it as soon as my rate limit resets (it takes ~3,500 calls and you get 5,000 an hour).

### CODE REVIEW

**Comment by kemitchell** [comment]
:+1: Reviewing now.

**Comment by beaugunderson** [comment]
Just fixed a bug in `github-package-json` (fixed in 2.2.0) so make sure you test with that if you test locally (searching in the default branch didn't work but searching among pull requests did, and there are actually a few where it's fixed but not deployed yet, like `microsoft/typescript`).

**Comment by beaugunderson** [comment]
Wow there are actually a ton that are fixed but not published; I updated my local copy:

http://beaugunderson.com/npm1k.html

(ran into rate limit around #650 though)

**Comment by kemitchell** [comment]
> Wow there are actually a ton that are fixed but not published

g1432189070313118260

:wink:

**Comment by beaugunderson** [comment]
(noting that I started that run with about ~1400 requests left in my rate limit, so fixing the validity check for master `package.json` actually significantly lowered the amount of total GitHub requests made, because if it's fixed in master pull requests are not searched)

**Pull request merged**
