### PR TITLE
use `jonschlinkert/parse-github-url` instead

### PR DESCRIPTION
**Pull request by tunnckoCore**
it is most complete and the best solution for parsing maybe 99.9% of all or all weird use cases.

see the coverage https://github.com/jonschlinkert/parse-github-url

### CODE REVIEW

**Comment by kemitchell** [comment]
@tunnckoCore, did you notice any bad links or other errors due to `github-url-to-object`?

**Comment by tunnckoCore** [comment]
there have in the wild and also noticed [that line](https://github.com/npm1k/npm1k.github.io/blob/master/bin/generate.js#L32) which mention that `git+http(s)` urls cant be parsed by github-url-to-object, which is weird, cuz if you `npm init` and just  write "foo/bar" for the repository input it will generate exactly that type of urls.

omg, so mistakes, im :sleepy:

**Comment by kemitchell** [comment]
Does `normalize-package-data` normalize all the relevant URLs?

**Comment by beaugunderson** [comment]
So I may have jumped the gun on the change I made to add the replacement (though it doesn't break anything); I tested via the [demo site](https://github-url-to-object.herokuapp.com) and that's where I ascertained that the `git+ssh://` URLs didn't work--but I think that might just be a bug in the demo site and not the actual module!

**Comment by kemitchell** [comment]
Thanks, @beaugunderson!

**Comment by kemitchell** [comment]
And thanks to you, too, @tunnckoCore! Happy to receive your PR.

**Comment by beaugunderson** [comment]
For example, if you try this URL in the demo site linked above it fails to parse:

`git+ssh://git@github.com:npm/npm.git`

And it looks like it is legitimately broken, so the `replace(/^git\+/, '')` call is needed:

```
> g = require('github-url-to-object')
[Function]
> g('git+ssh://git@github.com:npm/npm.git')
null
```

**Comment by beaugunderson** [comment]
Hmm... Even replacing `git+` in the test URL above fails because of the `:` later in the URL, so I think we should definitely merge this (I tested that it works with all the variations that fail above). :)

**Comment by tunnckoCore** [comment]
@kemitchell @beaugunderson that's why i made this pr and talking to use `parse-github-url`

see https://github.com/jonschlinkert/parse-github-url/blob/master/test.js

**Pull request merged**
